from datetime import date
from markdown_pdf import MarkdownPdf, Section


class AssemblerAgent:
    def __init__(self, **convertor_kwargs):
        self.pdf = MarkdownPdf(**convertor_kwargs)


    def add_title_page(self, topic: str) -> None:
        self.pdf.add_section(Section(
            f'# A Research Report on {topic}\n\n'
            '**Author:** Harshit Kumawat (Created using Agentic AI)\n'
            '**Disclamer:** This report is auto-generated by an LLM-powered research assistant. Human verification is recommended for critical use.\n'
            f'**Date of Creation:**'
        ))
